### PR TITLE
chore: upgrade all language-stylus dependencies and vscode config

### PR DESCRIPTION
**Pull request by iChenLei**
### This PR if for **`upgrade language-stylus project infrastructure`**

- [x] upgrade all `devDependencies` and `dependencies`, engines'vscode is `^1.59.0` now
- [x] rename displayName from `language-stylus` to `stylus` for better marketplace search reault rank
- [x] update .vscode config (e.g. tasks.json setting.json launch.json)
- [x] make .gitignore work ! ( ignore `out` dir generated file, that's bad for PR code review
- [x] add latest `vscode-css-languageservice` support

cc @d4rkr00t Ready for code review, thanks  

###  Next roadmap

- [ ] add color picker support for `.styl` file
- [ ] add unit test via [`@vscode/test-electron`](https://www.npmjs.com/package/@vscode/test-electron) and `github action ci`
- [ ] add `husky` `prettier` for better collaboration
- [ ] fix stylus syntax highlight related issue
- [ ] support stylus `@import` `@require` path autocomplete intellisense

### CODE REVIEW

**Review by d4rkr00t — APPROVED** [review]

**Comment by iChenLei** [comment]
Roadmap's task will implement in other pull request, all in one PR is hard to review. So if you have time, please merge this pull request and release a new version language-stylus. Thanks @d4rkr00t

**Comment by iChenLei** [comment]
Use `Squash and merge` for clean commits, thanks. You can set this config.



> dirty commits here

**Comment by iChenLei** [comment]
Use `Squash and merge` for clean commits, thanks. You can set this config.



> dirty commits here

**Comment by d4rkr00t** [comment]
Published :)

**Comment by iChenLei** [comment]
@d4rkr00t  Now, when vscode user search `stylus` keyword, our vscode extension will be No.1 in search result rank list.

**Comment by PodaruDragos** [comment]
Hey guys, thanks for doing this.
I have one question though. Why not move this repo to the official stylus github organization ?
Is that something that you @d4rkr00t don't want to do ?

This way stylus would have an official language-service and extension ( thus increasing trust and downloads from all of us )

**Comment by iChenLei** [comment]
@PodaruDragos Both language-stylus and stylus self lack maintenance for a while. Maintain work restart is not a easy work. I have become this vscode extension's development collaborator, transfer this extension to stylus official org is not important thing, Keep iteration is key.

**Pull request merged**
