### PR TITLE
Add autoclosing quotes

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by d4rkr00t** [comment]
I've checked, everything works fine. It would be great if you can change commit message to match commitizen style: 

screen shot 2016-05-16 at 16 50 49

It might be, for example:

``` sh
feat(*) Add autoclosing and surrounding pairs

Fix #3
```

You can do it by running: 

``` sh
git commit --amend
```

**Comment by ghost** [comment]
```
feat(*) Add autoclosing and surrounding pairs

Fix #3
```

A commit message exactly like that? new line and all?

**Comment by d4rkr00t** [comment]
Yes, second line for extra information.

**Comment by ghost** [comment]
if I change the message will be a conflict

**Comment by ghost** [comment]
never mind a 'push -f' solved the problem

**Comment by d4rkr00t** [comment]
👍

**Pull request merged**
